# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71e527dd4ccf05de0cea9c8325b4b08ce7e76cd8eb5e8c19c46e74d878b3707fb13db1c42e5e8877c38a5df0412dd0dd6c4efa2402cdaece74225f6dd77086ab

  #MAILGUN
  API_KEY_MAILGUN:  "pubkey-fcf20ad219c8e5f527b1c3f3c58ab5b0"
  DOMAIN_MAILGUN:   "sandboxb3e3cad4f88d41439ce00aab036a94d0.mailgun.org"
  API_BASE_URL:     "https://api.mailgun.net/v3/app661bab478eb74476bf1ee071138c34b7.mailgun.org"
  USERNAME_MAILGUN: "postmaster@sandboxb3e3cad4f88d41439ce00aab036a94d0.mailgun.org"
  PASSWORD_MAILGUN: "f468683557b00976167c56ac46703b4e"


test:
  secret_key_base: 7d6f919525fead74caf4ecad8107aedce6850eb2841b6aa7d8bbb0c52b9f8df21102bb9a6631e9f301cc41d82e9d6337293e0327328b119fac62a481a7185807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  #MAILGUN
  API_KEY_MAILGUN:  "pubkey-fcf20ad219c8e5f527b1c3f3c58ab5b0"
  DOMAIN_MAILGUN:   "sandboxb3e3cad4f88d41439ce00aab036a94d0.mailgun.org"
  API_BASE_URL:     "https://api.mailgun.net/v3/app661bab478eb74476bf1ee071138c34b7.mailgun.org"
  USERNAME_MAILGUN: "postmaster@sandboxb3e3cad4f88d41439ce00aab036a94d0.mailgun.org"
  PASSWORD_MAILGUN: "f468683557b00976167c56ac46703b4e"
